#! /usr/bin/env bash

use_python() {
  if [ -n "$(command -v pyenv)" ]; then
    local pyversion=$1
    pyenv local "${pyversion}"
  fi
}

layout_virtualenv() {
  local pyversion=$1
  local pvenv=$2
  if [ -n "$(command -v pyenv-virtualenv)" ]; then
    pyenv virtualenv --force --quiet "${pyversion}" "${pvenv}-${pyversion}"
  fi
  pyenv local --unset
}

layout_activate() {
  if [ -n "$(command -v pyenv)" ]; then
    # shellcheck source=/dev/null
    source "$(pyenv root)/versions/${1}/bin/activate"
  fi
}
