#! /usr/bin/env bash

if [ "$(command -v nodenv)" ]; then
  NODE_VERSIONS="$(nodenv root)/versions"
  NODE_VERSION_PREFIX=''
  export NODE_VERSIONS NODE_VERSION_PREFIX
fi

use_ruby() {
  if [ -n "$(command -v rbenv)" ]; then
    load_prefix "$(rbenv root)/versions/${1}"
    layout_ruby
  fi
}
