#! /usr/bin/env bash

# http://stuff-things.net/2014/12/16/working-with-emacsclient/
#
if [ -z "$SSH_CONNECTION" ]; then
  if [ "$(command -v code)" ]; then
    export EDITOR='code --wait'
  else
    export EDITOR='emacsclient -c'
  fi
  export ALTERNATE_EDITOR=''
else
  EDITOR=$(type -P emacs || type -P vim || type -P vi)
  export EDITOR
fi
export VISUAL=$EDITOR
