#! /usr/bin/env bash

if [ $(command -v brew) ]; then
  # If set, Homebrew will not send analytics. See: <https://docs.brew.sh/Analytics.html>
  export HOMEBREW_NO_ANALYTICS=1

  # If set, Homebrew will not permit redirects from secure HTTPS
  # to insecure HTTP.
  #
  # While ensuring your downloads are fully secure, this is likely
  # to cause from-source SourceForge, some GNU & GNOME based
  # formulae to fail to download.
  export HOMEBREW_NO_INSECURE_REDIRECT=1

  # abort installation of cask if no checksum is defined
  export HOMEBREW_CASK_OPTS=--require-sha

  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
fi
