#! /usr/bin/env bash

if "command -v pyenv" > /dev/null; then eval "$(pyenv init - --no-rehash bash)"; fi

if "command -v pyenv-virtualenv-init" > /dev/null; then eval "$(pyenv virtualenv-init - bash)"; fi
