#! /usr/bin/env bash

if [ "$(command -v pyenv)" ]; then
  export PYENV_ROOT="${HOME}/.pyenv"
  eval "$(pyenv init - --no-rehash bash)"

  if [ "$(command -v pyenv-virtualenv-init)" ]; then
    eval "$(pyenv virtualenv-init - bash)"
  fi
fi
